services:
  - type: web
    name: hypercrypt-api
    env: java
    plan: free
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/hypercrypt-1.0-SNAPSHOT.jar"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Bu, anahtarın loglarda görünmesini engeller
